services:
    Itis\DoctrineEntityBundle\EventListener\UrlConflictListener:
        calls:
            - [ setContainer,["@service_container"] ]
            - [ setDoctrine,["@doctrine"] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
